/** Product minima from spec §§6.3, 9.5, 10.1–10.3. Advance currentPhase at each gate. */
export default {
  currentPhase: 2,
  phases: { generators: 3, banks: 3, variants: 3, lessons: 7, interactives: 8 },
  sources: {
    generators: 'src/core/generators/index.ts',
    banks: 'src/core/banks/index.ts',
    variants: 'src/core/variants/index.ts',
    lessons: 'src/content/lessons',
    interactives: 'src/interactives/index.ts',
  },
  generators: {
    1: 4,
    2: 4,
    3: 4,
    4: 4,
    5: 4,
    6: 4,
    7: 4,
    8: 4,
    9: 4,
    10: 4,
    11: 3,
    12: 3,
    14: 4,
    15: 4,
    16: 4,
  },
  banks: { presentation: 12, document: 12 },
  variants: {
    minimum: 10,
    requiredIds: [
      'V01',
      'V02',
      'V03',
      'V04',
      'V05',
      'V06',
      'V07',
      'V08',
      'V09',
      'V10',
    ],
  },
  lessons: {
    minimum: 45,
    sections: {
      i1: 3,
      i2: 3,
      i3: 3,
      i4: 3,
      i5: 4,
      i6: 4,
      i7: 3,
      i8: 3,
      i9: 3,
      i10: 3,
      i11: 3,
      i12: 3,
      i13: 3,
      i14: 4,
    },
    blocks: [
      'LessonHeader',
      'Motivation',
      'Theory',
      'Interactive',
      'Examples',
      'Mistakes',
      'Quiz',
      'StreamLink',
      'CheatSheet',
    ],
    visualizations: 2,
    interactives: 1,
    examples: 3,
    mistakes: 3,
    quizQuestions: 5,
  },
  interactives: {
    '2d': {
      minimum: 18,
      requiredIds: [
        'text-volume',
        'bits-and-bytes',
        'code-decoder',
        'logic-builder',
        'shortest-path',
        'path-count',
        'fixed-executor',
        'program-tracer',
        'resource-address',
        'search-sets',
        'number-systems',
        'file-tree',
        'text-search',
        'file-masks',
        'document-lab',
        'slide-layout',
        'spreadsheet-lab',
        'robot-field',
      ],
    },
    '3d': {
      minimum: 5,
      levelsPerGame: 3,
      requiredIds: [
        'bit-warehouse',
        'packet-route',
        'robot-maze',
        'sorting-center',
        'logic-gates',
      ],
    },
  },
} as const;
